"""mod_units.py — receipts for 'what about mod ((+i)(-i))' (2026-09-10).
(1) (+i)(-i) = 1: mod 1 is the trivial ring Z/1 = {0} — total collapse (the opposite of mod infinity = no collapse).
(2) The non-trivial reading: mod the UNIT GROUP of Z[i] = {1, i, -1, -i}, cyclic of order 4 generated by i, whose one relation
    is i * (-i) = 1. Working mod units = working with IDEALS; on the angle side it is angle mod 90 degrees (the fold that made
    the Hecke tower canonical: the invariant is e^{4 i theta}).
(3) The nearby modulus that is a field: Z[i]/(1+i) = F_2 (a + bi -> a + b mod 2). Mod 2 = (1+i)^2: a 4-element ring where the
    ramified prime is nilpotent, (1+i)^2 = 2i == 0 mod 2 — the perpendicularity (1,1).(1,-1) = 0 has a mod-2 shadow."""
import cmath, math
i = complex(0, 1)
assert i * (-i) == 1 and (1 + i) * (1 - i) == 2 and (1 + i) ** 2 == 2 * i
print("(1) (+i)(-i) =", i * (-i), "-> 'mod 1': Z/1 = {0}; every integer == 0. Trivial ring, not a field (0 = 1).  [T]")
# (2) unit group
units = [1, i, -1, -i]
powers = [i ** k for k in range(4)]
assert {(round(z.real), round(z.imag)) for z in powers} == {(round(complex(u).real), round(complex(u).imag)) for u in units}
print("(2) units of Z[i]: {1, i, -1, -i} = <i>, order 4; relation i * (-i) = 1. Multiplying by a unit rotates by 90°.  [T]")
# gaussian primes up to units = ideals; folded angles
def gauss_factor(p):  # p = a^2 + b^2 for split p
    for a in range(1, int(p**0.5) + 1):
        b2 = p - a * a; b = int(round(b2 ** 0.5))
        if b * b == b2: return a, b
print("    prime ideals of Z[i] above small rational primes, and their angles mod 90° (unit-classes = ideals):")
for p in (2, 3, 5, 7, 11, 13, 17):
    if p == 2: print(f"      p = 2 : (1+i), ramified — 1 ideal, angle 45° mod 90° (the fold edge)")
    elif p % 4 == 3: print(f"      p = {p:>2}: ({p}), inert — 1 ideal, angle 0° mod 90° (on the axis)")
    else:
        a, b = gauss_factor(p); th = math.degrees(math.atan2(b, a))
        print(f"      p = {p:>2}: ({a}+{b}i), ({a}-{b}i), split — 2 ideals, angles ±{th:.2f}° mod 90° = {th % 90:.2f}° and {(-th) % 90:.2f}°; e^(4iθ) real part cos4θ = {math.cos(4*math.radians(th)):+.4f} = Re((a+bi)^4)/p^2")
# (3) residue rings
res_1pi = set()
for a in range(-3, 4):
    for b in range(-3, 4):
        res_1pi.add((a + b) % 2)      # (a + bi) mod (1+i): since i == 1 mod (1+i), a + bi == a + b
print("(3) Z[i]/(1+i): residues", sorted(res_1pi), "= F_2 (a + bi -> a + b mod 2): the field with TWO elements, parity.  [T]")
# Z[i]/(2): representatives {0, 1, i, 1+i}; (1+i)^2 = 2i == 0
reps = [complex(0, 0), complex(1, 0), complex(0, 1), complex(1, 1)]
def red2(z): return complex(z.real % 2, z.imag % 2)
sq = red2((1 + i) ** 2)
print(f"    Z[i]/(2) has 4 elements {{0, 1, i, 1+i}}; (1+i)^2 = 2i == {sq} mod 2 — nilpotent: the ramified prime squares to zero; not a field.  [T]")
print("    So: mod 1 = nothing left; mod (1+i) = parity (F_2); mod 2 = parity with a nilpotent seam; mod p (p = 3 mod 4) = F_{p^2}; mod a split factor = F_p.")
print("ALL CHECKS PASSED")
